server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.220.200:3308/ai_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: cpc!23#@
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod
