server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    url: jdbc:clickhouse://myhost:8123/demo
    username: demo
    password: demo123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 5000
      validation-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
