server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.220.200:3308/ai_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: cpc!23#@
  profiles:
    active: prod
